import { QUESTION_TITLE } from '../constants'

export const questionTitle = (name) => {
   switch (name) {
      case QUESTION_TITLE.SELECT_REAL_ENGLISH_WORDS:
         return QUESTION_TITLE.SELECT_REAL_ENGLISH_WORDS

      case QUESTION_TITLE.TYPE_WHAT_YOU_HEAR:
         return QUESTION_TITLE.TYPE_WHAT_YOU_HEAR

      case QUESTION_TITLE.DESCRIBE_IMAGE:
         return QUESTION_TITLE.DESCRIBE_IMAGE

      case QUESTION_TITLE.RESPOND_IN_AT_LEAST_N_WORDS:
         return QUESTION_TITLE.RESPOND_IN_AT_LEAST_N_WORDS

      case QUESTION_TITLE.RECORD_SAYING:
         return QUESTION_TITLE.RECORD_SAYING

      case QUESTION_TITLE.HIGHLIGHTS_THE_ANSWER:
         return QUESTION_TITLE.HIGHLIGHTS_THE_ANSWER

      case QUESTION_TITLE.SELECT_MAIN_IDEA:
         return QUESTION_TITLE.SELECT_MAIN_IDEA

      case QUESTION_TITLE.SELECT_THE_BEST_TITLE:
         return QUESTION_TITLE.SELECT_THE_BEST_TITLE
      default:
         return name
   }
}
